CREATE DATABASE app CHARSET utf8mb4;
USE app;

CREATE TABLE users(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(100) NOT NULL,
img VARCHAR(255),
roles VARCHAR(50)
)ENGINE=InnoDB;
